### ISSUE TITLE
app folder

### ISSUE THREAD

**Issue by PhillippOhlandt** [dantleech/bolt-fixtures#3]
Hey,

is there a reason for the app folder being in this repo?

**Comment by dantleech** [comment]
Its for the [functional tests](https://github.com/dantleech/bolt-fixtures/blob/master/tests/Functional/ApplicationTestCase.php). To be fair it appeared there by automatically, but I decided to keep it as I often take a similar approach in analagous situations.

**Comment by dantleech** [comment]
But the `cache` folder should certainly be ignored :)

**Comment by PhillippOhlandt** [comment]
Ok, fair point when it's needed for tests.
